### ISSUE TITLE
[IoM] [Default] Mainline Candidate Requirements

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/Isle_of_Mists#1]
Isle of Mists
- [x] Side 5 healer gets no traits. Otherwise a meat shield/CC unit if resilient/dextrous
- [x] Revise Dwarven Arcanister Wave
- [x] Consider +100 starting gold
- [x] Void border fix...
- [x] Add some more weather maps (heavy flooding / heavy snowfall / etc) 

Both DF revision and IoM
- [x] Fix units walking over unwalkable, perhaps revise that code segment in general.

**Comment by nemaara** [comment]
Not necessarily a requirement, but consider making a different weather pattern for IoM. Since this is an isle, you could have something like regular flooding, heavy flooding, heavy snowfall, etc. This also makes water units more viable on both the player and enemy side.

**Comment by knyghtmare** [comment]
Closed since I added them all in and now, I have playtest to see if there are any fatal crashes.
